
import java.awt.Container;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hieu bach
 */
public class ChangeFont extends javax.swing.JDialog {

    /**
     * Creates new form ChangeFont
     */
    Vector font;
    Vector size;
    MTE parent;
    public ChangeFont(java.awt.Frame parent, boolean modal, String fontName, int style, int sizeFont) {
        super(parent, modal);
        initComponents();
        setTitle("Change font");
        font=new Vector();
        size=new Vector<>();
        setSize();
        setFont();
        setStyle(style);
        setCurrentFont(fontName);
        this.parent=(MTE) parent;
        String tempSize = Integer.toString(sizeFont);
        txtSize.setText(tempSize);

        setVisible(true);
    }

    public void setCurrentFont(String fontName) {
        txtFont.setText(fontName);
        int pos = 0;
        for (int i = 0; i < font.size(); i++) {
            if (fontName.compareToIgnoreCase((String) font.get(i)) == 0) {
                pos = i;
            }
        }
        listFont.setSelectedIndex(pos);
    }

    public void setStyle(int style) {
        if (style == Font.BOLD) {
            txtStyle.setText("Bold");
        } else if (style == Font.PLAIN) {
            txtStyle.setText("Plain");
        } else {
            txtStyle.setText("Italic");
        }
        listStyle.setSelectedValue(txtStyle.getText(), true);
    }

    public void setFont() {
        GraphicsEnvironment localGraphicsEnvironment = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fontName = localGraphicsEnvironment.getAvailableFontFamilyNames();
        for (int i = 0; i < fontName.length; i++) {
            font.add(fontName[i]);
        }
        listFont.setListData(font);
    }

    public void setSize() {
        for (int i = 10; i <= 50; i += 5) {
            size.add(i);
        }
        listSize.setListData(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listFont = new javax.swing.JList<>();
        txtFont = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStyle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listStyle = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listSize = new javax.swing.JList<>();
        txtSample = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listFont.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listFontMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listFont);

        txtFont.setEditable(false);

        jLabel1.setText("Font");

        jLabel2.setText("Font Style");

        txtStyle.setEditable(false);

        listStyle.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Plain", "Bold", "Italic" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listStyle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listStyleMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listStyle);

        jLabel3.setText("Size");

        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });

        listSize.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listSizeMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(listSize);

        txtSample.setText("aAbBcdD");
        txtSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSampleActionPerformed(evt);
            }
        });

        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSample)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStyle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(txtSize)))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btOk)
                .addGap(66, 66, 66)
                .addComponent(btCancel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(txtFont)
                            .addComponent(txtSize))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(34, 34, 34)
                        .addComponent(txtSample, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btOk)
                            .addComponent(btCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setFontSample() {
        String font = txtFont.getText();
        String temp = txtStyle.getText();
        String size = txtSize.getText();
        int style = 0;
        if (temp.compareToIgnoreCase("plain") == 0) {
            style = Font.PLAIN;
        } else if (temp.compareToIgnoreCase("bold") == 0) {
            style = Font.BOLD;
        } else {
            style = Font.ITALIC;
        }
        int tmpSize = (int) Float.parseFloat(size);
        txtSample.setFont(new Font(font, style, tmpSize));
    }
    private void txtSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSampleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSampleActionPerformed

    private void listFontMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFontMousePressed
        // TODO add your handling code here:
        txtFont.setText(listFont.getSelectedValue());
        setFontSample();
    }//GEN-LAST:event_listFontMousePressed

    private void listStyleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listStyleMousePressed
        // TODO add your handling code here:
        txtStyle.setText(listStyle.getSelectedValue());
        setFontSample();
    }//GEN-LAST:event_listStyleMousePressed

    private void listSizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSizeMousePressed
        // TODO add your handling code here: 
       int pos= listSize.getSelectedIndex();
       int number= (int) size.get(pos);
       txtSize.setText(Integer.toString(number));
        setFontSample();
    }//GEN-LAST:event_listSizeMousePressed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
        setFontSample();
    }//GEN-LAST:event_txtSizeActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
        String temp=txtStyle.getText();
        int style=0;
        if (temp.compareToIgnoreCase("plain") == 0) {
            style = Font.PLAIN;
        } else if (temp.compareToIgnoreCase("bold") == 0) {
            style = Font.BOLD;
        } else {
            style = Font.ITALIC;
        }
        parent.setFont(txtFont.getText(), style, Float.parseFloat(txtSize.getText()));
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listFont;
    private javax.swing.JList<String> listSize;
    private javax.swing.JList<String> listStyle;
    private javax.swing.JTextField txtFont;
    private javax.swing.JTextField txtSample;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtStyle;
    // End of variables declaration//GEN-END:variables
}
